[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[http]
maxBodySize = "50M"

[[services]]
[services.php]
command = "php-fpm"
maxBodySize = "50M"

[services.php.environment]
upload_max_filesize = "50M"
post_max_size = "50M"
